"""
Feature Store — Central repository for article features.

The Feature Store is the single source of truth for article feature data.
All datasets, predictions, and analytics are generated from features
stored here. It is NOT an AI feature store — it simply persists
article features consumed by prediction models and recommendations.

Core dataclass:
    - NewsFeatures: a single article's complete feature set

Central class:
    - FeatureStore: upsert, query, and aggregate article features

Usage::

    store = FeatureStore()
    store.upsert(NewsFeatures(
        article_id="a1",
        source_name="reuters",
        source_quality=0.85,
        final_score=0.72,
    ))

    # For prediction
    features = store.get_by_article_id("a1")

    # For dataset generation
    approved = store.query(decision="APPROVED", source_name="reuters")

    # For analytics
    stats = store.stats_by_source("reuters")
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass(frozen=True)
class NewsFeatures:
    """A single article's complete feature set.

    This is the atomic unit of the Feature Store.
    Every article gets ONE NewsFeatures record.
    Datasets are generated by querying the Feature Store.

    Attributes:
        id: Unique feature record ID.
        article_id: Reference to the source article.
        source_name: Name of the news source.
        title: Article title.

        # Quality features (0.0 - 1.0)
        source_quality: How trustworthy the source is.
        keyword_strength: Relevance of extracted keywords.
        freshness: How recent the article is (decays over time).
        duplicates: Similarity to previously seen articles (0=unique, 1=duplicate).
        topic_strength: Strength of topic association.
        category_strength: Strength of category association.
        historical_success: Historical approval rate for similar articles.

        # Computed features
        confidence: Model's confidence in the prediction.
        final_score: Weighted combination of all features.

        # Decision (nullable — set after human review)
        editor_decision: APPROVED, REJECTED, or None (pending).

        # Metadata
        created_at: When this feature record was created.
        metadata: Additional context (arbitrary key-value pairs).
    """

    id: str = ""
    article_id: str = ""
    source_name: str = ""
    title: str = ""

    # Quality features (0.0 - 1.0)
    source_quality: float = 0.0
    keyword_strength: float = 0.0
    freshness: float = 0.0
    duplicates: float = 0.0
    topic_strength: float = 0.0
    category_strength: float = 0.0
    historical_success: float = 0.0

    # Computed features
    confidence: float = 0.0
    final_score: float = 0.0

    # Decision (nullable — set after human review)
    editor_decision: str | None = None  # APPROVED, REJECTED, None

    # Metadata
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = field(default_factory=dict)


class FeatureStore:
    """Central feature repository. All datasets are generated from here.

    NOT an AI feature store. Simply persists article features
    that will be consumed by prediction models, datasets, and recommendations.

    Internal storage:
        - _store: dict[str, NewsFeatures] keyed by feature id
        - _by_article: dict[str, str] mapping article_id → feature_id

    Usage::

        store = FeatureStore()
        store.upsert(NewsFeatures(article_id="a1", source_quality=0.85, ...))

        # For prediction
        features = store.get_by_article_id("a1")

        # For dataset generation
        approved = store.query(decision="APPROVED", source_name="reuters")

        # For analytics
        stats = store.stats_by_source("reuters")
    """

    def __init__(self) -> None:
        self._store: dict[str, NewsFeatures] = {}  # keyed by id
        self._by_article: dict[str, str] = {}  # article_id → feature_id

    def upsert(self, features: NewsFeatures) -> None:
        """Insert or update features for an article.

        If an article already has features, the existing record is replaced.
        This guarantees ONE feature record per article.
        """
        if features.article_id in self._by_article:
            # Update existing
            old_id = self._by_article[features.article_id]
            self._store[old_id] = features
        else:
            # Insert new
            self._store[features.id] = features
            self._by_article[features.article_id] = features.id

    def get_by_id(self, feature_id: str) -> NewsFeatures | None:
        """Get a feature record by its unique ID."""
        return self._store.get(feature_id)

    def get_by_article_id(self, article_id: str) -> NewsFeatures | None:
        """Get a feature record by the article it describes."""
        fid = self._by_article.get(article_id)
        return self._store.get(fid) if fid else None

    def query(
        self,
        source_name: str | None = None,
        decision: str | None = None,
        min_score: float | None = None,
        max_score: float | None = None,
        limit: int | None = None,
    ) -> list[NewsFeatures]:
        """Query features with optional filters.

        All filters are optional and compose with AND semantics.
        Results are unsorted — use list operations for ordering.

        Args:
            source_name: Filter by news source name.
            decision: Filter by editor decision (APPROVED, REJECTED, or None for pending).
            min_score: Minimum final_score (inclusive).
            max_score: Maximum final_score (inclusive).
            limit: Maximum number of results to return.

        Returns:
            List of matching NewsFeatures.
        """
        results = list(self._store.values())
        if source_name:
            results = [f for f in results if f.source_name == source_name]
        if decision:
            results = [f for f in results if f.editor_decision == decision]
        if min_score is not None:
            results = [f for f in results if f.final_score >= min_score]
        if max_score is not None:
            results = [f for f in results if f.final_score <= max_score]
        if limit:
            results = results[:limit]
        return results

    def count(self) -> int:
        """Total number of feature records."""
        return len(self._store)

    def count_by_decision(self) -> dict[str, int]:
        """Count features grouped by editor decision.

        Returns:
            Dict with keys: APPROVED, REJECTED, PENDING (for None decisions).
        """
        counts: dict[str, int] = {}
        for f in self._store.values():
            key = f.editor_decision or "PENDING"
            counts[key] = counts.get(key, 0) + 1
        return counts

    def stats_by_source(self, source_name: str) -> dict[str, Any]:
        """Get aggregated statistics for a specific source.

        Args:
            source_name: Name of the news source.

        Returns:
            Dict with count, avg_score, min_score, max_score,
            approved, rejected, and pending counts.
            Returns {"count": 0} if no features exist for the source.
        """
        features = [f for f in self._store.values() if f.source_name == source_name]
        if not features:
            return {"count": 0}
        scores = [f.final_score for f in features]
        return {
            "count": len(features),
            "avg_score": sum(scores) / len(scores),
            "min_score": min(scores),
            "max_score": max(scores),
            "approved": sum(1 for f in features if f.editor_decision == "APPROVED"),
            "rejected": sum(1 for f in features if f.editor_decision == "REJECTED"),
            "pending": sum(1 for f in features if f.editor_decision is None),
        }

    def clear(self) -> None:
        """Remove all feature records."""
        self._store.clear()
        self._by_article.clear()
